version: '3'

networks:
  node:

services:
  node:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    image: node:20.11-alpine
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - node